# Generated by Django 5.0.6 on 2024-06-10 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id_boleta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('detallle', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle_boleta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boleta')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.libro')),
            ],
        ),
    ]
