# Generated by Django 5.0.6 on 2024-06-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
