# Generated by Django 5.0.6 on 2024-06-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_libro_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
