# Generated by Django 5.0.6 on 2024-06-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_apellido_usuario_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='RUT',
        ),
    ]
